template = "https://github.com/giellalt/template-lang-und"
rev_id = 271
template_sha = "58889500fa56906fc67098b753f74968988220af"

[replacements]
__GLOTTOLOG_ID__ = "dogr1252"
__REPO__ = "lang-dgr"
__UND2C__ = "dgr"
__UNDEFINED__ = "Dogrib"
__UND__ = "dgr"
